/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EntropyInputProof } from "./EntropyInputProof";
export type { IEntropyOracle } from "./IEntropyOracle";
